[logstreamer_nova]
type = "LogstreamerInput"
log_directory = "/var/log/nova"
file_match = '(?P<Service>.+)\.log\.?(?P<Index>\d*)?(.gz)?'
differentiator = ['nova','_','Service']
priority = ["^Index"]
decoder = "openstack"
oldest_duration = "168h"

[openstack]
type = "SandboxDecoder"
filename = "lua_modules/decoders/openstack.lua"
module_directory = "/usr/share/heka/lua_modules;/usr/share/heka/lua_modules/common"

